development: &default
  adapter: postgresql
  encoding: unicode
  database: synop_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  min_messages: warning
  timeout: 5000

test:
  <<: *default
  database: synop_test

production:
  adapter: postgresql
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  database: synop_production
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000
